com.mchange.v2.naming.objectFactoryWhitelist=com.mchange.v2.c3p0.impl.C3P0JavaBeanObjectFactory
com.mchange.v2.naming.referenceableJavaBeanClassWhitelist=\
    com.mchange.v2.c3p0.DriverManagerDataSource,\
    com.mchange.v2.c3p0.PoolBackedDataSource,\
    com.mchange.v2.c3p0.ComboPooledDataSource,\
    com.mchange.v2.c3p0.WrapperConnectionPoolDataSource,\
    com.mchange.v2.c3p0.JndiRefConnectionPoolDataSource,\
    com.mchange.v2.c3p0.JndiRefForwardingDataSource,\
    com.mchange.v2.c3p0.debug.CloseLoggingComboPooledDataSource,\
    com.mchange.v2.c3p0.debug.ConstructionLoggingComboPooledDataSource,\
    com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource,\
    com.mchange.v2.c3p0.test.FreezableDriverManagerDataSource,\
    com.mchange.v2.c3p0.test.AlwaysFailDataSource






