com.mchange.v2.naming.objectFactory.whitelist.c3p0-internal=com.mchange.v2.c3p0.impl.C3P0JavaBeanObjectFactory
com.mchange.v2.naming.referenceableJavaBeanClass.whitelist.c3p0-internal=\
    com.mchange.v2.c3p0.DriverManagerDataSource,\
    com.mchange.v2.c3p0.PoolBackedDataSource,\
    com.mchange.v2.c3p0.ComboPooledDataSource,\
    com.mchange.v2.c3p0.WrapperConnectionPoolDataSource,\
    com.mchange.v2.c3p0.JndiRefConnectionPoolDataSource,\
    com.mchange.v2.c3p0.JndiRefForwardingDataSource,\
    com.mchange.v2.c3p0.debug.CloseLoggingComboPooledDataSource,\
    com.mchange.v2.c3p0.debug.ConstructionLoggingComboPooledDataSource,\
    com.mchange.v2.c3p0.debug.AfterCloseLoggingComboPooledDataSource

# we include here for convenience the com.mchange.v2.c3p0.loom.*
# classes bundled with the optional c3p0-loom distribution
com.mchange.v2.reflect.byNameInstantiation.whitelist.c3p0-internal=\
    com.mchange.v2.c3p0.impl.AuthMaskingProperties,\
    com.mchange.v2.c3p0.impl.DefaultTaskRunnerFactory,\
    com.mchange.v2.c3p0.impl.DefaultConnectionTester,\
    com.mchange.v2.c3p0.WrapperConnectionPoolDataSource,\
    com.mchange.v2.c3p0.DriverManagerDataSource,\
    com.mchange.v2.c3p0.FixedThreadPoolExecutorTaskRunnerFactory,\
    com.mchange.v2.c3p0.loom.UninstrumentedVirtualThreadPerTaskTaskRunnerFactory,\
    com.mchange.v2.c3p0.loom.VirtualThreadPerTaskExecutorTaskRunnerFactory,\
    com.mchange.v2.c3p0.example.IsValidOnlyConnectionTester30,\
    com.mchange.v2.c3p0.example.InitSqlConnectionCustomizer







